---
kind: pipeline
type: digitalocean
name: cloneing

token:
  from_secret: token
username:
  from_secret: username
password:
  from_secret: password

server:
  image: ubuntu-24-10-x64
  size: s-1vcpu-512mb-10gb
  region: sfo3

steps:
#  - name: cloneing the git repo
#    commands:
#    - git clone https://github.com/RohitDarekar816/Team---django-notes-app.git

#  - name: List the git repo files
#    commands:
#    - ls

- name: Checking the docker version
  commands:
  - sudo apt install docker.io -y
#  - name: Installing docker
#    commands:
#    - docker build -t notes-app .

#  - name: run docker 
#    commands:
#    - docker run -d -p 8000:8000 notes-app:latest

- name: Installing doctl
  commands:
  - wget https://github.com/digitalocean/doctl/releases/download/v1.119.0/doctl-1.119.0-linux-amd64.tar.gz
  - tar xf doctl-1.119.0-linux-amd64.tar.gz
  - sudo mv doctl /usr/local/bin
  # - doctl registry login
  - cat my_password.txt | docker login --u info@iconmagazine.in foo --password-stdin registry.digitalocean.com

# - name: Login to docker registry 
#  commands:
#  - docker login registry.digitalocean.com

trigger:
  event:
    - push
    - pull_request
  branch:
    - main 