#this s test
---
kind: pipeline
name: add-ssh-key

steps:
  - name: add-digitalocean-ssh-key
    image: curlimages/curl:latest
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: DIGITALOCEAN_TOKEN
    commands:
      - |
        curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
        -d '{"name":"This is a test key","public_key":"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIT+GpvMKvRZbDJoFXwGDToYp/4RlJlUook6E9UOZdzv example"}' \
        "https://api.digitalocean.com/v2/account/keys"
        
---
kind: pipeline
type: digitalocean
name: Building docker image for django

token:
    from_secret: token

server:
    image: ubuntu-24-10-x64
    size: s-1vcpu-512mb-10gb
    region: sfo3

# pipeline start here
steps:
    - name: cloneing the git repo
      commands:
          - git clone https://github.com/RohitDarekar816/sample-nodejs.git

    - name: Installing the docker
      commands:
          - sudo apt install docker.io -y

    - name: Building docker image
      commands:
          - docker build -t team---django-notes-app .

    - name: Run docker image in detach mode on temp server
      commands:
          - docker run -d team---django-notes-app

    - name: login to digitalocean via api token
      environment:
          DO_USERNAME:
              from_secret: DO_USERNAME
          DO_API_TOKEN:
              from_secret: token
      commands:
          - echo $DO_API_TOKEN | docker login registry.digitalocean.com --username $DO_USERNAME --password-stdin
          #- docker tag team---django-notes-app registry.digitalocean.com/pipelineaws/team---django-notes-app
          #- docker push registry.digitalocean.com/pipelineaws/team---django-notes-app

trigger:
    event:
        - push
        - pull_request
    branch:
        - main
