---
kind: pipeline
type: digitalocean
name: cloneing

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
- name: cloneing the git repo
  commands:
  - git clone https://github.com/RohitDarekar816/Team---django-notes-app.git

- name: List the git repo files
  commands:
  - ls

- name: Checking the docker version
  commands:
  - docker --version

- name: Installing docker
  commands:
  - sudo docker build -t notes-app:latest /root/Team---django-notes-app
---
kind: pipeline
type: docker
name: default

steps:
- name: Clone Git
  commands:
  - git clone https://github.com/RohitDarekar816/Team---django-notes-app.git

- name: Building the docke file
  image: notes-app
  commands:
  - docker build -t notes-app:latest /root/Team---django-notes-app 

trigger:
  event:
    - push
    - pull_request
  branch:
    - main 