---
kind: pipeline
type: digitalocean
name: cloneing

token:
  from_secret: token

server:
  image: ubuntu-24-10-x64
  size: s-1vcpu-512mb-10gb
  region: sfo3

steps:
- name: cloneing the git repo
  commands:
  - git clone https://github.com/RohitDarekar816/Team---django-notes-app.git

- name: List the git repo files
  commands:
  - ls

- name: Checking the docker version
  commands:
  - sudo apt install docker.io -y

- name: Installing docker
  commands:
  - docker build -t notes-app /root/Team---django-notes-app

- name: run docker 
  commands:
  - docker run -d -p 8000:8000 notes-app:latest 

trigger:
  event:
    - push
    - pull_request
  branch:
    - main 